{% set name = "edalize" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 58ceb08be8bd966df14f0deebbaf5648972cddf1372db3d8f7f7db1e87545752

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - jinja2 >=3

test:
  imports:
    - edalize

about:
  home: https://github.com/olofk/edalize
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Edalize is a library for interfacing EDA tools, primarily for FPGA development

extra:
  recipe-maintainers:
    - hmaarrfk
