{% set name = "edalize" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 12aaa8be8f9fe8bcbb934008232ce8fbe7e5e4968c5c5b92dae35106ba2c3591

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools-scm
  run:
    - python >=3.6
    - jinja2 >=3

test:
  imports:
    - edalize

about:
  home: https://github.com/olofk/edalize
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Edalize is a library for interfacing EDA tools, primarily for FPGA development

extra:
  recipe-maintainers:
    - hmaarrfk
