{% set name = "edalize" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9fe1ddbf0d860d78e437dbd3bc951bda616e4f79803a189a4c64f7a828ca9162

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - jinja2 >=3

test:
  requires:
    - python {{ python_min }}
  imports:
    - edalize

about:
  home: https://github.com/olofk/edalize
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Edalize is a library for interfacing EDA tools, primarily for FPGA development

extra:
  recipe-maintainers:
    - hmaarrfk
