{% set name = "edalize" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 222f34d3b80ef377763dbb99e0cf56c8a11976b236e97e30be0f66feaf811b26

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - jinja2 >=2.8,!=2.11.0,!=2.11.1
    - pytest >=3.3.0

test:
  imports:
    - edalize

about:
  home: https://github.com/olofk/edalize
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Edalize is a library for interfacing EDA tools, primarily for FPGA development

extra:
  recipe-maintainers:
    - hmaarrfk
