{% set name = "edalize" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2c460f754406e00029f629dac4d362bc5275d0357a04b18b5b43803bf5f95ba8

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - jinja2 >=2.8
    - pytest >=3.3.0

test:
  imports:
    - edalize

about:
  home: https://github.com/olofk/edalize
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Edalize is a library for interfacing EDA tools, primarily for FPGA development'

extra:
  recipe-maintainers:
    - hmaarrfk
