{% set name = "edalize" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 57427b4b13d45693ec58023766fba33f66f88cfb65487b61e5499f809a0e93a2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools-scm
  run:
    - importlib-metadata >=1.4
    - python >={{ python_min }}
    - jinja2 >=3

test:
  requires:
    - python {{ python_min }}
  imports:
    - edalize

about:
  home: https://github.com/olofk/edalize
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Edalize is a library for interfacing EDA tools, primarily for FPGA development

extra:
  recipe-maintainers:
    - hmaarrfk
