travis:
  secure:
    BINSTAR_TOKEN: cuBdCcTZd7jpuOd4Z+1V+ueDvKfq6r7I46wkHTYWgKmYnwrHWaIsQX9J8YJKZPXPM1qzlHoxWDhSzpPOyPUbiSYcVKI4LrJw6MfYB/XyeYU7dKTiKd+EX4mdALiNQHk1ivJ2kmIjl+v3CvhLg86uGFVMj0tjQ04xVxW2RsBjFV8vcZz0FI1LSI7ejd/c7Jo5DfRxYS0QPzwqbn5rNWzJUt8ggIz09dOVNbv/EW+OfN2CUqoMuw4T7X35LEWc7mzAJBsVk9ag478QE30yrNLGqlN4qFpaaTIeWNVTo9RQt7zNcw2kPI1IKK22LtK9gHVMtM5Z4I+Uo6j3bzQCFZuFVr5Q8soMLdY2Lu1LUDW8h4xACccNm7OiwNcSIbWNu6gHot2yuou7A36lmF8K/LeAsvo3M7Oper8/CIq7Wfv2F3wIEezNcESZzL3OCTktN5jsiLlf7vFlD7nJuJ5l/UGBGu1y1nN2mrfnLs/M1Y28uM+5nMjA/4wS4VxE4WxJP1NLtuPQRJmcxIR6d9AQveGwGZZ6BjwSDT6THGWb4bUMSLtemZerq+y32jhpxazro5aps78b6ki2vOfhrjEdVeE2F0fnNcGwDoKXV+jDbjQ1+PHiuQINVGLAmlL8ZfQSdU93/DaSXNUtvQv/DNY/F/5LTKmp0/UBcufOPR6xzENQPgk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
